### ISSUE TITLE
Return error when serial is already out of warranty

### ISSUE THREAD

**Issue by ngjordan** [chilcote/warranty#5]
Hi Chilcote, great work on the script, I've been having issue with serials that already past their warranty coverage, the script return and error and stop the whole batch processing.

Here is the error log
Traceback (most recent call last):
  File "/Users/xxxx/Desktop/New folder/Warranty.py", line 160, in <module>
    main()
  File "/Users/xxxx/Desktop/New folder/Warranty.py", line 146, in main
    (model, date, status) = scrape_warranty_site(serial, not args.quit_on_error)
  File "/Users/xxxx/Desktop/New folder/Warranty.py", line 93, in scrape_warranty_site
    date   = parser.parse(line.split('Date: ')[1].split('<br/')[0])
IndexError: list index out of range

Thank you!

**Comment by chilcote** [comment]
I can't replicate this with my test list of a few hundred serials, most of which are out of warranty.  Can you give me a sample serial (or the file) that fails? (if you don't want to put it in public like this feel free to email me (my username -> gmail)). Also the line numbers in the error don't seem to match up... are you on the most recent commit?

**Comment by ngjordan** [comment]
Hi, Im using this serial actually its an iPhone 012572000148829

**Comment by chilcote** [comment]
Huh... I never thought to try this with iphones... but hey, it works (for me at least).  Try a git pull --rebase to make sure you're up to date on the script.
-----

$ ./warranty 012572000148829
Serial Number:       012572000148829
Product Description: iPhone 3GS
Expires:             Expired
Status:              Inactive
ASD Version:         Undetermined

**Comment by ngjordan** [comment]
Ok will try thank you!

**Comment by ngjordan** [comment]
Got it working! thanks!

**Comment by chilcote** [comment]
Glad to hear it, thanks.
