### ISSUE TITLE
404 Returned

### ISSUE THREAD

**Issue by csteelatgburg** [chilcote/warranty#6]
Apple has updated the self care website and the script now returns a 404 error when it runs.

**Comment by chilcote** [comment]
Yeah, with this change there's no longer a way to scrape the selfsolve warranty site. I'll update the script to show estimated date of purchase instead since that's all we can really do without gsx access.

**Comment by chilcote** [comment]
Updated the script to estimate manufacture date, and estimate applecare and warranty status.

**Comment by jgstew** [comment]
Related: http://openradar.appspot.com/radar?id=4998891128750080
